version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sociclone-postgres
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB={DB_DATABASE}
    volumes:
      - sociclone-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    network_mode: "host"
    volumes:
      - sociclone-dragonflydata:/data





volumes:
  sociclone-dragonflydata:
  sociclone-postgres-data: